//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKTEMPLATE
    {
        public CHECKTEMPLATE()
        {
            this.CHECKTEMPLATEITEM = new HashSet<CHECKTEMPLATEITEM>();
        }
    
        public string CHECKTEMPLATECODE { get; set; }
        public string CHECKTEMPLATENAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<CHECKTEMPLATEITEM> CHECKTEMPLATEITEM { get; set; }
    }
}
