//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKTEMPLATEITEM
    {
        public long ID { get; set; }
        public string CHECKTEMPLATECODE { get; set; }
        public string CHECKITEMCODE { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string ORGID { get; set; }
    
        public virtual CHECKTEMPLATE CHECKTEMPLATE { get; set; }
    }
}
