//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKITEM
    {
        public string ORGID { get; set; }
        public string CHECKITEMCODE { get; set; }
        public string CHECKITEMNAME { get; set; }
        public string CHECKITEMNAMEEN { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string NORMALVALUE { get; set; }
        public string LOWBOUND { get; set; }
        public string UPBOUND { get; set; }
        public string UNITNAME { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
