//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_ASSESSVALUE
    {
        public long ID { get; set; }
        public Nullable<long> SEQNO { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string VALUEDESC { get; set; }
        public string RECORDBY { get; set; }
        public string EXECUTEBY { get; set; }
    
        public virtual DC_REGCPL DC_REGCPL { get; set; }
    }
}
