//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_CAREPLANACTIVITY
    {
        public int CANO { get; set; }
        public Nullable<int> CPNO { get; set; }
        public string DIAPR { get; set; }
        public string PR { get; set; }
        public string ACTIVITY { get; set; }
        public string SYSACTION { get; set; }
    
        public virtual DC_CAREPLANPROBLEM DC_CAREPLANPROBLEM { get; set; }
    }
}
