//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_DAYLIFECAREREC
    {
        public DC_DAYLIFECAREREC()
        {
            this.DC_DAYLIFECAREDTL = new HashSet<DC_DAYLIFECAREDTL>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public string RESIDENTNO { get; set; }
        public string REGNAME { get; set; }
        public string SEX { get; set; }
        public string NURSEAIDES { get; set; }
        public Nullable<int> WEEKNUMBER { get; set; }
        public Nullable<System.DateTime> WEEKSTARTDATE { get; set; }
        public string CONTACTMATTERS { get; set; }
        public string FAMILYMESSAGE { get; set; }
        public string SOCIALWORKER { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<bool> DELFLAG { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_DAYLIFECAREDTL> DC_DAYLIFECAREDTL { get; set; }
    }
}
