//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_EVALQUESTION
    {
        public DC_EVALQUESTION()
        {
            this.DC_EVALQUESTIONRESULT = new HashSet<DC_EVALQUESTIONRESULT>();
        }
    
        public long RECORDID { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string REGNO { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string QUESTIONCODE { get; set; }
        public Nullable<int> EVALNUMBER { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string EVALRESULT { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORGID { get; set; }
    
        public virtual DC_NURSEINGPLANEVAL DC_NURSEINGPLANEVAL { get; set; }
        public virtual ICollection<DC_EVALQUESTIONRESULT> DC_EVALQUESTIONRESULT { get; set; }
    }
}
