//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_NOTE
    {
        public int NOTEID { get; set; }
        public string ACTIONUSERCODE { get; set; }
        public string NOTENAME { get; set; }
        public string NOTECONTENT { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<sbyte> ISSHOW { get; set; }
        public string ORGID { get; set; }
    }
}
