//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_NURSEINGLIFECAREDTL
    {
        public long SEQNO { get; set; }
        public Nullable<long> ID { get; set; }
        public string ACTIVITY9 { get; set; }
        public string ACTIVITY11 { get; set; }
        public string ACTIVITY14 { get; set; }
        public string ACTIVITY15 { get; set; }
        public string ACTIVITY16 { get; set; }
        public Nullable<decimal> BODYTEMPERATURE { get; set; }
        public Nullable<int> PULSE { get; set; }
        public Nullable<int> BREATH { get; set; }
        public Nullable<int> SBP { get; set; }
        public Nullable<int> DBP { get; set; }
        public string MEDICINE { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string DAYOFWEEK { get; set; }
        public string HOLIDAYFLAG { get; set; }
    
        public virtual DC_NURSEINGLIFECAREREC DC_NURSEINGLIFECAREREC { get; set; }
    }
}
