//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_QUESTION
    {
        public DC_QUESTION()
        {
            this.DC_QUESTIONITEM = new HashSet<DC_QUESTIONITEM>();
            this.DC_QUESTIONVALUE = new HashSet<DC_QUESTIONVALUE>();
        }
    
        public int QUESTIONID { get; set; }
        public string QUESTIONNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string QUESTIONCODE { get; set; }
        public Nullable<bool> ISSHOW { get; set; }
        public string QUESTIONDESC { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_QUESTIONITEM> DC_QUESTIONITEM { get; set; }
        public virtual ICollection<DC_QUESTIONVALUE> DC_QUESTIONVALUE { get; set; }
    }
}
