//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_QUESTIONITEM
    {
        public int ITEMID { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string ITEMNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual DC_QUESTION DC_QUESTION { get; set; }
    }
}
