//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGEVALQUESTION
    {
        public DC_REGEVALQUESTION()
        {
            this.DC_REGQUESTIONDATA = new HashSet<DC_REGQUESTIONDATA>();
        }
    
        public int SEQ { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public Nullable<int> EVALRECID { get; set; }
    
        public virtual DC_REGQUESTIONEVALREC DC_REGQUESTIONEVALREC { get; set; }
        public virtual ICollection<DC_REGQUESTIONDATA> DC_REGQUESTIONDATA { get; set; }
    }
}
