//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGCHECKRECORDDATA
    {
        public long DATAID { get; set; }
        public Nullable<long> RECORDID { get; set; }
        public string CHECKITEMCODE { get; set; }
        public string CHECKITEMVALUE { get; set; }
        public string LOWBOUND { get; set; }
        public string UPBOUND { get; set; }
        public string SEVERITYNAME { get; set; }
    
        public virtual DC_REGCHECKRECORD DC_REGCHECKRECORD { get; set; }
    }
}
