//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGCHECKRECORD
    {
        public DC_REGCHECKRECORD()
        {
            this.DC_REGCHECKRECORDDATA = new HashSet<DC_REGCHECKRECORDDATA>();
        }
    
        public long RECORDID { get; set; }
        public string REGNO { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string CHECKTEMPLATECODE { get; set; }
        public string ACTIONUSERCODE { get; set; }
        public Nullable<bool> ISABNORMAL { get; set; }
        public Nullable<bool> TRACESTATUS { get; set; }
        public Nullable<System.DateTime> TRACEDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<DC_REGCHECKRECORDDATA> DC_REGCHECKRECORDDATA { get; set; }
    }
}
