//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGLIFEQUALITYEVAL
    {
        public int ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string HEALTH { get; set; }
        public string ENERGY { get; set; }
        public string MOOD { get; set; }
        public string LIVINGCONDITION { get; set; }
        public string MEMORY { get; set; }
        public string FAMILY { get; set; }
        public string MERRY { get; set; }
        public string FRIENDS { get; set; }
        public string SELF { get; set; }
        public string FAMILYABILITY { get; set; }
        public string ENTERTAINMENT { get; set; }
        public string MONEY { get; set; }
        public string WHOLELIFE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string REGNO { get; set; }
        public string ORGID { get; set; }
    }
}
