//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGNOTERECORD
    {
        public long RECORDID { get; set; }
        public string ACTIONUSERCODE { get; set; }
        public Nullable<System.DateTime> NOTEDATE { get; set; }
        public string REGNO { get; set; }
        public Nullable<int> NOTEID { get; set; }
        public string NOTENAME { get; set; }
        public string NOTECONTENT { get; set; }
        public Nullable<sbyte> VIEWSTATUS { get; set; }
        public Nullable<System.DateTime> VIEWDATE { get; set; }
        public string ORGID { get; set; }
    }
}
