//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REGVISITRECORD
    {
        public long RECORDID { get; set; }
        public string ACTIONUSERCODE { get; set; }
        public Nullable<System.DateTime> VISITDATE { get; set; }
        public string REGNO { get; set; }
        public string VISITNAME { get; set; }
        public string VISITCONTENT { get; set; }
        public string ORGID { get; set; }
    }
}
