//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_REFERRALLISTS
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string SIOLOGICALSTATE { get; set; }
        public string PROBLEMSTATEMENT { get; set; }
        public string REFERRALPURPOSE { get; set; }
        public string DOCUMENTINFO { get; set; }
        public Nullable<System.DateTime> REFERRALDATE { get; set; }
        public string SOCIALWORKER { get; set; }
        public string SUPERVISOR { get; set; }
        public string REFERRALUNIT { get; set; }
        public string REFERRALRESULT { get; set; }
        public Nullable<System.DateTime> REPLYDATE { get; set; }
        public string UNITCONTACTOR { get; set; }
        public string UNITPHONE { get; set; }
        public string UNITFAX { get; set; }
        public string UNITNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual DC_IPDREG DC_IPDREG { get; set; }
    }
}
