//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_TASKREMIND
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> ASSIGNDATE { get; set; }
        public string ASSIGNEDBY { get; set; }
        public string ASSIGNEDNAME { get; set; }
        public string ASSIGNEE { get; set; }
        public string ASSIGNNAME { get; set; }
        public string CONTENT { get; set; }
        public Nullable<bool> RECSTATUS { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public string UNFINISHREASON { get; set; }
        public Nullable<System.DateTime> PERFORMDATE { get; set; }
        public string URL { get; set; }
        public Nullable<bool> NEWRECFLAG { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string ORGID { get; set; }
    }
}
