//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class DC_TEAMACTIVITYDTL
    {
        public int ID { get; set; }
        public Nullable<int> SEQNO { get; set; }
        public string TITLENAME { get; set; }
        public string ITEMNAME { get; set; }
    
        public virtual DC_TEAMACTIVITY DC_TEAMACTIVITY { get; set; }
    }
}
