//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BEDBASIC
    {
        public string BEDNO { get; set; }
        public string BEDDESC { get; set; }
        public string ROOMNO { get; set; }
        public string BEDCLASS { get; set; }
        public string FLOOR { get; set; }
        public string DEPTNO { get; set; }
        public string BEDTYPE { get; set; }
        public string BEDKIND { get; set; }
        public string BEDSTATUS { get; set; }
        public string SEXTYPE { get; set; }
        public string PRESTATUS { get; set; }
        public string INSBEDFLAG { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
        public Nullable<long> FEENO { get; set; }
    }
}
