//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CONSULTCALLBACK
    {
        public long ID { get; set; }
        public Nullable<long> CONSULTRECID { get; set; }
        public Nullable<System.DateTime> CALLBACKTIME { get; set; }
        public string INTERVIEWEE { get; set; }
        public string INTERVIEWREC { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    
        public virtual LTC_CONSULTREC LTC_CONSULTREC { get; set; }
    }
}
