//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_HANDOVERRECORD
    {
        public LTC_HANDOVERRECORD()
        {
            this.LTC_HANDOVERDTL = new HashSet<LTC_HANDOVERDTL>();
        }
    
        public long ID { get; set; }
        public Nullable<System.DateTime> HANDOVERDATE { get; set; }
        public Nullable<int> NEWCOMER { get; set; }
        public Nullable<int> TRANSFERSOCIETY { get; set; }
        public Nullable<int> TRANSFERMINITER { get; set; }
        public Nullable<int> TRANSFERDISABLED { get; set; }
        public Nullable<int> OUTOVERALL { get; set; }
        public Nullable<int> OUTRETURN { get; set; }
        public Nullable<int> OUTSTILL { get; set; }
        public Nullable<int> ACTUALPOPULATION { get; set; }
        public Nullable<int> INNAISOCIETY { get; set; }
        public Nullable<int> INNAIMINITER { get; set; }
        public Nullable<int> INNAIDISABLED { get; set; }
        public Nullable<int> INNAIOVERALL { get; set; }
    
        public virtual ICollection<LTC_HANDOVERDTL> LTC_HANDOVERDTL { get; set; }
    }
}
