//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_LOOKOVER
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> LOOKOVERTIME { get; set; }
        public string ITEMCODE { get; set; }
        public string FLOORID { get; set; }
        public string LOOKOVERPHOTOS { get; set; }
        public string CONTENT { get; set; }
        public string RECORDBY { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDETELE { get; set; }
    
        public virtual LTC_WORKITEM LTC_WORKITEM { get; set; }
    }
}
