//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHECKRECDTL
    {
        public long ID { get; set; }
        public string CHECKTYPE { get; set; }
        public string CHECKITEM { get; set; }
        public string CHECKRESULTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string EVALCOMBO { get; set; }
        public Nullable<long> RECORDID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
    
        public virtual LTC_CHECKREC LTC_CHECKREC { get; set; }
    }
}
