//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PINMONEY
    {
        public int ID { get; set; }
        public string IENO { get; set; }
        public string ITEMSUMMARY { get; set; }
        public string IETPYE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> IEDATE { get; set; }
        public Nullable<System.DateTime> FACTDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public int REGNO { get; set; }
        public long FEENO { get; set; }
        public string ORGID { get; set; }
    }
}
