//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_SCENARIO
    {
        public LTC_SCENARIO()
        {
            this.LTC_SCENARIO_ITEM = new HashSet<LTC_SCENARIO_ITEM>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SCENARIO { get; set; }
        public int CATEGORYID { get; set; }
        public string CATEGORYNAME { get; set; }
    
        public virtual ICollection<LTC_SCENARIO_ITEM> LTC_SCENARIO_ITEM { get; set; }
    }
}
