//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PROPOSALDISSCUSS
    {
        public LTC_PROPOSALDISSCUSS()
        {
            this.LTC_PROPOSALDISSCUSSREC = new HashSet<LTC_PROPOSALDISSCUSSREC>();
        }
    
        public long RECORDID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> PROPOSALDATE { get; set; }
        public string PROPOSALBY { get; set; }
        public Nullable<System.DateTime> NEXTPROPOSALDATE { get; set; }
        public string PERSONALHIST { get; set; }
        public string PROBLEMANALYSIS { get; set; }
        public string RESOURCEEVAL { get; set; }
        public string PROCESSPLAN { get; set; }
        public string ASSESSMENTS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string TITLE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_PROPOSALDISSCUSSREC> LTC_PROPOSALDISSCUSSREC { get; set; }
    }
}
