//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PIPELINE
    {
        public long SEQ { get; set; }
        public string KIND { get; set; }
        public string FEATHER { get; set; }
        public string AGUGE { get; set; }
        public string NAME { get; set; }
    }
}
