//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_VISITHOSPITAL
    {
        public LTC_VISITHOSPITAL()
        {
            this.LTC_VISITDEPT = new HashSet<LTC_VISITDEPT>();
            this.LTC_VISITDOCTOR = new HashSet<LTC_VISITDOCTOR>();
        }
    
        public string HOSPNO { get; set; }
        public string HOSPNAME { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_VISITDEPT> LTC_VISITDEPT { get; set; }
        public virtual ICollection<LTC_VISITDOCTOR> LTC_VISITDOCTOR { get; set; }
    }
}
