//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NSCPL
    {
        public LTC_NSCPL()
        {
            this.LTC_ASSESSVALUE = new HashSet<LTC_ASSESSVALUE>();
            this.LTC_NSCPLACTIVITY = new HashSet<LTC_NSCPLACTIVITY>();
            this.LTC_NSCPLGOAL = new HashSet<LTC_NSCPLGOAL>();
        }
    
        public long SEQNO { get; set; }
        public string EMPNO { get; set; }
        public string CPSOURCE { get; set; }
        public string CPTYPE { get; set; }
        public string CPLEVEL { get; set; }
        public string CPDIAG { get; set; }
        public string NSDESC { get; set; }
        public string CPCAUSE { get; set; }
        public string CPREASON { get; set; }
        public string FINISHFLAG { get; set; }
        public string CPRESULT { get; set; }
        public string DESCRIPTION { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<int> NEEDDAYS { get; set; }
        public Nullable<int> TOTALDAYS { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> TARGETDATE { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<LTC_ASSESSVALUE> LTC_ASSESSVALUE { get; set; }
        public virtual ICollection<LTC_NSCPLACTIVITY> LTC_NSCPLACTIVITY { get; set; }
        public virtual ICollection<LTC_NSCPLGOAL> LTC_NSCPLGOAL { get; set; }
    }
}
