//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_DOCTORCHECKREC
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string DEPTNO { get; set; }
        public string DOCNO { get; set; }
        public string CONSCIOUSNESS { get; set; }
        public string PHYSIOLOGY { get; set; }
        public Nullable<decimal> BODYTEMP { get; set; }
        public Nullable<int> PULSE { get; set; }
        public Nullable<int> BP { get; set; }
        public Nullable<int> BPH { get; set; }
        public Nullable<decimal> OXYGEN { get; set; }
        public Nullable<decimal> BS { get; set; }
        public string DISPOSITIONDESC { get; set; }
        public string OTHERDESC { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
