//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_UNPLANWEIGHTIND
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<decimal> THISWEIGHT { get; set; }
        public Nullable<decimal> THISHEIGHT { get; set; }
        public Nullable<decimal> WAIST { get; set; }
        public Nullable<decimal> HIPLINE { get; set; }
        public Nullable<System.DateTime> THISRECDATE { get; set; }
        public Nullable<decimal> LASTWEIGHT { get; set; }
        public Nullable<decimal> DIFFVALUE { get; set; }
        public Nullable<decimal> DIFFVALUERATE { get; set; }
        public Nullable<System.DateTime> LASTRECDATE { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public string BMIRESULTS { get; set; }
        public Nullable<decimal> B3WEIGHT { get; set; }
        public Nullable<decimal> B3DIFFVALUE { get; set; }
        public Nullable<decimal> B3DIFFVALUERATE { get; set; }
        public Nullable<decimal> B6WEIGHT { get; set; }
        public Nullable<decimal> B6DIFFVALUE { get; set; }
        public Nullable<decimal> B6DIFFVALUERATE { get; set; }
        public Nullable<bool> UNPLANFLAG { get; set; }
        public string RECORDBY { get; set; }
        public string ORGID { get; set; }
        public Nullable<decimal> KNEELEN { get; set; }
    }
}
