//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PROPOSALDISSCUSSREC
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> MEETINGDATE { get; set; }
        public string RECORDBY { get; set; }
        public string MEETCHAIRMAN { get; set; }
        public string ATTENDANCE { get; set; }
        public string GUIDTEACHER { get; set; }
        public string MEETINGADDRESS { get; set; }
        public string MEETINGTITLE { get; set; }
        public string QUESTION { get; set; }
        public string QUESTIONDIAG { get; set; }
        public string TEACHERSUGGESTION { get; set; }
        public string QUESTIONDISSCUSSION { get; set; }
        public string DECISIONS { get; set; }
        public string MOTION { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<long> RECORDID { get; set; }
    
        public virtual LTC_PROPOSALDISSCUSS LTC_PROPOSALDISSCUSS { get; set; }
    }
}
