//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGRELATIONDTL
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string CONTREL { get; set; }
        public string KINSHIP { get; set; }
        public string RELATIONTYPE { get; set; }
        public Nullable<bool> LIVINGFLAG { get; set; }
        public string EDUCATION { get; set; }
        public string MERRYFLAG { get; set; }
        public string HEALTHFLAG { get; set; }
        public string DEATHFLAG { get; set; }
        public string WORKCODE { get; set; }
        public Nullable<bool> ECONOMYFLAG { get; set; }
        public string IDNO { get; set; }
        public string ZIP { get; set; }
        public string ADDRESS { get; set; }
        public string ADDRESS2 { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string SKYPE { get; set; }
        public string MSN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string ECONOMYABILITY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
    }
}
