//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_MAKERITEMLIMITEDVALUE
    {
        public int LIMITEDVALUEID { get; set; }
        public Nullable<decimal> LIMITEDVALUE { get; set; }
        public string LIMITEDVALUENAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<bool> ISDEFAULT { get; set; }
        public int LIMITEDID { get; set; }
    }
}
