//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BEDSOREREC
    {
        public LTC_BEDSOREREC()
        {
            this.LTC_BEDSORECHGREC = new HashSet<LTC_BEDSORECHGREC>();
        }
    
        public long SEQ { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string OCCURCHANCE { get; set; }
        public Nullable<System.DateTime> OCCURDATE { get; set; }
        public string DEGREE { get; set; }
        public string EVALUTEBY { get; set; }
        public string INSPECTIONRESULT { get; set; }
        public Nullable<System.DateTime> REVOCERYDATE { get; set; }
        public string EVENTREVIEW { get; set; }
        public Nullable<bool> REVOCERYFLAG { get; set; }
        public string REVOCERYDESC { get; set; }
        public string PICT1 { get; set; }
        public string PICT2 { get; set; }
        public string PICT3 { get; set; }
        public string PICT4 { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_BEDSORECHGREC> LTC_BEDSORECHGREC { get; set; }
    }
}
