//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NCIEVALUATE
    {
        public LTC_NCIEVALUATE()
        {
            this.LTC_NCIEVALUATEDTL = new HashSet<LTC_NCIEVALUATEDTL>();
        }
    
        public int NCIEVALUATEID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string NAME { get; set; }
        public string SSNO { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public string RESIDENTNO { get; set; }
        public string BEDNO { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string UPDATEBY { get; set; }
    
        public virtual ICollection<LTC_NCIEVALUATEDTL> LTC_NCIEVALUATEDTL { get; set; }
    }
}
