//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NURSINGHANDOVER
    {
        public int ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string CONTENT_D { get; set; }
        public string CONTENT_E { get; set; }
        public string CONTENT_N { get; set; }
        public Nullable<System.DateTime> RECDATE_D { get; set; }
        public Nullable<System.DateTime> RECDATE_E { get; set; }
        public Nullable<System.DateTime> RECDATE_N { get; set; }
        public string RECORDBY_D { get; set; }
        public string RECORDBY_E { get; set; }
        public string RECORDBY_N { get; set; }
        public string NURSE_D { get; set; }
        public string NURSE_E { get; set; }
        public string NURSE_N { get; set; }
        public Nullable<bool> PRINTFLAG { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
