//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_MONTHLYPAYBILLRECORD
    {
        public int ID { get; set; }
        public string BILLID { get; set; }
        public string YEARMONTH { get; set; }
        public long FEENO { get; set; }
        public decimal PAYEDAMOUNT { get; set; }
        public System.DateTime COMPSTARTDATE { get; set; }
        public System.DateTime COMPENDDATE { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
