//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NEWREGENVADAPTATION
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<System.DateTime> W1EVALDATE { get; set; }
        public Nullable<long> INFORMFLAG { get; set; }
        public Nullable<long> COMMFLAG { get; set; }
        public string INTERPERSONAL { get; set; }
        public string PARTICIPATION { get; set; }
        public string COORDINATION { get; set; }
        public string EMOTION { get; set; }
        public string RESISTANCE { get; set; }
        public string HELP { get; set; }
        public Nullable<int> WEEK { get; set; }
        public string PROCESSACTIVITY { get; set; }
        public string TRACEREC { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public string EVALUATION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ORGID { get; set; }
    }
}
