//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_MODULES
    {
        public LTC_MODULES()
        {
            this.LTC_ROLES = new HashSet<LTC_ROLES>();
        }
    
        public string MODULEID { get; set; }
        public string MODULENAME { get; set; }
        public string URL { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUPERMODULEID { get; set; }
        public string TARGET { get; set; }
        public string ICON { get; set; }
        public Nullable<int> ROOTORDER { get; set; }
        public Nullable<bool> ISSYS { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string SYSTYPE { get; set; }
    
        public virtual ICollection<LTC_ROLES> LTC_ROLES { get; set; }
    }
}
