//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ZIPFILE
    {
        public int ID { get; set; }
        public string CITY { get; set; }
        public string TOWN { get; set; }
        public string POSTCODE { get; set; }
    }
}
