//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ORGFLOOR
    {
        public LTC_ORGFLOOR()
        {
            this.LTC_ORGROOM = new HashSet<LTC_ORGROOM>();
        }
    
        public string FLOORID { get; set; }
        public string FLOORNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_ORGROOM> LTC_ORGROOM { get; set; }
    }
}
