//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_FIXEDCOST
    {
        public int ID { get; set; }
        public System.DateTime STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<bool> ISENDCHARGES { get; set; }
        public int COSTITEMID { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public string ITEMUNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> REPEATCOUNT { get; set; }
        public Nullable<System.DateTime> GENERATEDATE { get; set; }
        public int REGNO { get; set; }
        public long FEENO { get; set; }
        public string ORGID { get; set; }
    
        public virtual LTC_COSTITEM LTC_COSTITEM { get; set; }
    }
}
