//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_IPDREGOUT
    {
        public long FEENO { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<bool> CLOSEFLAG { get; set; }
        public string CLOSEREASON { get; set; }
        public Nullable<bool> DEADFLAG { get; set; }
        public string DEADREASON { get; set; }
        public Nullable<System.DateTime> DEADDATE { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public Nullable<int> TOTALDAY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual LTC_IPDREG LTC_IPDREG { get; set; }
    }
}
