//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHARGEGROUP
    {
        public LTC_CHARGEGROUP()
        {
            this.LTC_CHARGEGROUP_CHARGEITEM = new HashSet<LTC_CHARGEGROUP_CHARGEITEM>();
            this.LTC_CHARGEGROUP_CHARGERECORD = new HashSet<LTC_CHARGEGROUP_CHARGERECORD>();
            this.LTC_CHARGEGROUP_RESIDENT = new HashSet<LTC_CHARGEGROUP_RESIDENT>();
        }
    
        public string CHARGEGROUPID { get; set; }
        public string CHARGEGROUPNAME { get; set; }
        public string CHARGEGROUPDESC { get; set; }
        public string CHARGEGROUPPERIOD { get; set; }
        public bool CANAUTORENEW { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public string NSID { get; set; }
    
        public virtual ICollection<LTC_CHARGEGROUP_CHARGEITEM> LTC_CHARGEGROUP_CHARGEITEM { get; set; }
        public virtual ICollection<LTC_CHARGEGROUP_CHARGERECORD> LTC_CHARGEGROUP_CHARGERECORD { get; set; }
        public virtual ICollection<LTC_CHARGEGROUP_RESIDENT> LTC_CHARGEGROUP_RESIDENT { get; set; }
    }
}
