//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NUTRTIONEVAL
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string SEX { get; set; }
        public string RESIDENGNO { get; set; }
        public string BEDNO { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public string DISEASEDIAG { get; set; }
        public string CHEWDIFFCULT { get; set; }
        public string SWALLOWABILITY { get; set; }
        public string EATPATTERN { get; set; }
        public string DIGESTIONPROBLEM { get; set; }
        public string FOODTABOO { get; set; }
        public string ACTIVITYABILITY { get; set; }
        public string PRESSURESORE { get; set; }
        public string EDEMA { get; set; }
        public string CURRENTDIET { get; set; }
        public string EATAMOUNT { get; set; }
        public string WATER { get; set; }
        public string SUPPLEMENTS { get; set; }
        public string SNACK { get; set; }
    }
}
