//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ROLES
    {
        public LTC_ROLES()
        {
            this.LTC_MODULES = new HashSet<LTC_MODULES>();
            this.LTC_USERS = new HashSet<LTC_USERS>();
        }
    
        public string ROLEID { get; set; }
        public string ROLENAME { get; set; }
        public string ROLETYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string ORGID { get; set; }
        public string SYSTYPE { get; set; }
    
        public virtual ICollection<LTC_MODULES> LTC_MODULES { get; set; }
        public virtual ICollection<LTC_USERS> LTC_USERS { get; set; }
    }
}
