//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_GROUPACTIVITYREC
    {
        public int ID { get; set; }
        public string ACTIVITYNAME { get; set; }
        public string ACTIVITYTYPE { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public Nullable<int> EVENTHOURS { get; set; }
        public string EVENTPLACE { get; set; }
        public string LEADERNAME { get; set; }
        public string LEADERNAME1 { get; set; }
        public string LEADERNAME2 { get; set; }
        public string ACTIVITYRESULTS { get; set; }
        public Nullable<int> EVALRESULTS { get; set; }
        public Nullable<int> ATTENDNUMBER { get; set; }
        public string GROUPCOMPETENCE { get; set; }
        public string INDIVIDUALSUMMARY { get; set; }
        public string SUGGESTION { get; set; }
        public string DESCRIPTION { get; set; }
        public string PICTURE1 { get; set; }
        public string PICTURE2 { get; set; }
        public string ATTENDNO { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
