//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTDTL
    {
        public long ID { get; set; }
        public string COSTNO { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public Nullable<int> COSTSOURCE { get; set; }
        public string ITEMTYPE { get; set; }
        public Nullable<System.DateTime> OCCURTIME { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> TOTALPRICE { get; set; }
        public Nullable<bool> SELFFLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public int REGNO { get; set; }
        public long FEENO { get; set; }
        public string ORGID { get; set; }
        public Nullable<long> BILLID { get; set; }
    }
}
