//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHECKTYPE
    {
        public LTC_CHECKTYPE()
        {
            this.LTC_CHECKITEM = new HashSet<LTC_CHECKITEM>();
        }
    
        public string TYPECODE { get; set; }
        public string TYPENAME { get; set; }
    
        public virtual ICollection<LTC_CHECKITEM> LTC_CHECKITEM { get; set; }
    }
}
