//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHECKREC
    {
        public LTC_CHECKREC()
        {
            this.LTC_CHECKRECDTL = new HashSet<LTC_CHECKRECDTL>();
        }
    
        public long RECORDID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public string RECORDBY { get; set; }
        public string HOSPNAME { get; set; }
        public string CHECKRESULTS { get; set; }
        public Nullable<System.DateTime> NEXTCHECKDATE { get; set; }
        public string NEXTCHECKBY { get; set; }
        public string TRACESTATE { get; set; }
        public string DISEASEDESC { get; set; }
        public Nullable<bool> XRAYFLAG { get; set; }
        public Nullable<bool> NORMALFLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_CHECKRECDTL> LTC_CHECKRECDTL { get; set; }
    }
}
