//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_LABEXAMREC
    {
        public long ID { get; set; }
        public Nullable<long> SEQNO { get; set; }
        public string UNIT { get; set; }
        public Nullable<System.DateTime> EXAMDATE { get; set; }
        public string EXAMTYPE { get; set; }
        public Nullable<System.DateTime> RPTDATE { get; set; }
        public string FUNGUS { get; set; }
        public string EXAMRESULTS { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
    
        public virtual LTC_INFECTIONIND LTC_INFECTIONIND { get; set; }
    }
}
