//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BILLV2PAY
    {
        public LTC_BILLV2PAY()
        {
            this.LTC_BILLV2 = new HashSet<LTC_BILLV2>();
        }
    
        public int BILLPAYID { get; set; }
        public decimal SELFPAY { get; set; }
        public decimal NCIITEMTOTALCOST { get; set; }
        public decimal NCIPAY { get; set; }
        public decimal NCIITEMSELFPAY { get; set; }
        public Nullable<decimal> ACCOUNTBALANCEPAY { get; set; }
        public string OPERATOR { get; set; }
        public string PAYER { get; set; }
        public string PAYMENTTYPE { get; set; }
        public string INVOICENO { get; set; }
        public long FEENO { get; set; }
        public Nullable<System.DateTime> PAYTIME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<LTC_BILLV2> LTC_BILLV2 { get; set; }
    }
}
