//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGHEALTH
    {
        public long FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ALLERGY { get; set; }
        public string HEALTHINFO { get; set; }
        public string EATHABITS { get; set; }
        public Nullable<decimal> CAL { get; set; }
        public Nullable<bool> COOKFLAG { get; set; }
        public string NOTCOOKREASON { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<bool> CATHETERFLAG { get; set; }
        public Nullable<bool> TRACHEOSTOMYFLAG { get; set; }
        public Nullable<bool> NASOGASTRICFLAG { get; set; }
        public string DEMANDDESC { get; set; }
        public string ORGID { get; set; }
        public string CATHETERSIZE { get; set; }
        public string TRACHEOSTOMYSIZE { get; set; }
        public string NASOGASTRICSIZE { get; set; }
        public Nullable<bool> STOMAFLAG { get; set; }
        public string STOMASIZE { get; set; }
    }
}
