//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ACTIVEPERIOD_HIST
    {
        public string ORGID { get; set; }
        public Nullable<int> PERIODLENGTH { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<System.DateTime> ACTUALENDDATE { get; set; }
    }
}
