//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_DOCTOREVALREC
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public string DOCNAME { get; set; }
        public string SMOKINGHISTORY { get; set; }
        public string DRINKWINE { get; set; }
        public string CHEWINGBETELNUT { get; set; }
        public string DRUGFLAG { get; set; }
        public string REGULAREXERCISE { get; set; }
        public string OTHERDESC { get; set; }
        public string DISEASEDESC { get; set; }
        public string MEDICALHISTORY { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> WAIST { get; set; }
        public Nullable<decimal> HIPLINE { get; set; }
        public Nullable<decimal> ARMSAROUND { get; set; }
        public Nullable<int> VITALSIGNS { get; set; }
        public string CONSCIOUSNESS { get; set; }
        public string EMOTION { get; set; }
        public string COMMUNICATION { get; set; }
        public string EYESIGHT { get; set; }
        public string HEARING { get; set; }
        public string TACTILESENSATION { get; set; }
        public string PAINSTATE { get; set; }
        public string PAINTYPE { get; set; }
        public string PAINNATURE { get; set; }
        public string DIETSTATE { get; set; }
        public string DIETWAY { get; set; }
        public string DIETPATTERN { get; set; }
        public string DRUGUSESTATE { get; set; }
        public string MOVEMENT { get; set; }
        public string SLEEP { get; set; }
        public Nullable<bool> SLEEPPILLS { get; set; }
        public Nullable<bool> WOUNDFLAG { get; set; }
        public string WOUNDHEAL { get; set; }
        public string WOUNDPART { get; set; }
        public string WOUNDSIZE { get; set; }
        public string SKINDESC { get; set; }
        public string FALSETEETH { get; set; }
        public string LYMPHNODE { get; set; }
        public string BREAST { get; set; }
        public string PLEURAL { get; set; }
        public string SYMMETRICALCHEST { get; set; }
        public string HEART { get; set; }
        public string HEARTNOISE { get; set; }
        public string HEARTARRHYTHMIA { get; set; }
        public string ABDOMEN { get; set; }
        public string LIMBS { get; set; }
        public string NERVOUSSYSTEM { get; set; }
        public string CHECKDATA { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
