//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGDISEASEHISDTL
    {
        public int ID { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public string OTHERITEMNAME { get; set; }
        public string SCENARIOOPTIONIDS { get; set; }
        public Nullable<System.DateTime> SICKTIME { get; set; }
        public string ORGITREATMENTHOS { get; set; }
        public string EXPECTTRANSFERTO { get; set; }
        public Nullable<bool> HAVECURE { get; set; }
    
        public virtual LTC_REGDISEASEHIS LTC_REGDISEASEHIS { get; set; }
    }
}
