//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NCIDEDUCTION
    {
        public int ID { get; set; }
        public string BILLID { get; set; }
        public int DEDUCTIONTYPE { get; set; }
        public string DEBITMONTH { get; set; }
        public Nullable<int> LEAVEID { get; set; }
        public Nullable<int> DEBITDAYS { get; set; }
        public double AMOUNT { get; set; }
        public string DEDUCTIONREASON { get; set; }
        public Nullable<int> DEDUCTIONSTATUS { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATTIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public string ORGID { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual LTC_BILLV2 LTC_BILLV2 { get; set; }
        public virtual LTC_LEAVEHOSP LTC_LEAVEHOSP { get; set; }
    }
}
