//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_IPDORDER
    {
        public long ORDERNO { get; set; }
        public Nullable<int> ORDERTYPE { get; set; }
        public Nullable<int> FEECODE { get; set; }
        public Nullable<int> ITEMTYPE { get; set; }
        public string ACREMARK { get; set; }
        public Nullable<decimal> TAKEQTY { get; set; }
        public Nullable<int> TAKEDAY { get; set; }
        public string TAKEFREQ { get; set; }
        public string TAKEWAY { get; set; }
        public Nullable<int> CONFIRMFLAG { get; set; }
        public Nullable<System.DateTime> CONFIRMDATE { get; set; }
        public Nullable<int> CHECKFLAG { get; set; }
        public Nullable<System.DateTime> CHECKDATE { get; set; }
        public Nullable<int> STOPFLAG { get; set; }
        public Nullable<System.DateTime> STOPDATE { get; set; }
        public Nullable<int> STOPCHECKFLAG { get; set; }
        public Nullable<System.DateTime> STOPCHECKDATE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> EXECTIMES { get; set; }
        public Nullable<System.DateTime> BILLDATE { get; set; }
        public Nullable<int> DELETEFLAG { get; set; }
        public Nullable<int> FIRSTDAYQUANTITY { get; set; }
        public Nullable<long> SORTNUMBER { get; set; }
        public string CHARGEGROUPID { get; set; }
        public string DOCTORNO { get; set; }
        public string NURSENO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ORGID { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
