//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_IPDCLOSECASE
    {
        public long FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string PALLIATIVECARE { get; set; }
        public string PALLIATIVECAREFILE { get; set; }
        public Nullable<bool> CLOSEFLAG { get; set; }
        public Nullable<System.DateTime> CLOSEDATE { get; set; }
        public string CLOSEREASON { get; set; }
        public Nullable<bool> TRAININGDATA { get; set; }
        public Nullable<bool> WILLSFLAG { get; set; }
        public string WILLSDESC { get; set; }
        public string BODYPROCESS { get; set; }
        public string BODYPROCESSDESC { get; set; }
        public string BODYKEEPPLACE { get; set; }
        public string ESTATEEXECUTOR { get; set; }
        public string ESTATEPROCESS { get; set; }
        public string FUNERALPROCESS { get; set; }
        public string BODYPROCESS_EXE { get; set; }
        public string BODYPROCESSDESC_EXE { get; set; }
        public string BODYKEEPPLACE_EXE { get; set; }
        public string ESTATEEXECUTOR_EXE { get; set; }
        public string ESTATEPROCESS_EXE { get; set; }
        public Nullable<bool> DEATHFLAG { get; set; }
        public Nullable<System.DateTime> DEATHDATE { get; set; }
        public string DEATHREASON { get; set; }
        public string DEATHPLACE { get; set; }
        public Nullable<System.DateTime> MEETINGDATE { get; set; }
        public string PARTICIPANTS { get; set; }
        public string MEETINGNOTES { get; set; }
        public string ORGID { get; set; }
    }
}
