//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGACTIVITYREQUEVAL
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> INDATE { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public string CARER { get; set; }
        public string VISION { get; set; }
        public string SMELL { get; set; }
        public string SENSATION { get; set; }
        public string TASTE { get; set; }
        public string HEARING { get; set; }
        public string UPPERLIMB { get; set; }
        public string LOWERLIMB { get; set; }
        public string HALLUCINATION { get; set; }
        public string DELUSION { get; set; }
        public string ATTENTION { get; set; }
        public string DIRECTIONSENSE { get; set; }
        public Nullable<sbyte> DIRECTMAN { get; set; }
        public Nullable<sbyte> DIRECTTIME { get; set; }
        public Nullable<sbyte> DIRECTADDRESS { get; set; }
        public string COMPREHENSION { get; set; }
        public string MEMORY { get; set; }
        public Nullable<sbyte> MEMORYFLAG { get; set; }
        public string EXPRESSION { get; set; }
        public string OTHERNARRATIVE { get; set; }
        public string EMOTION { get; set; }
        public string SELF { get; set; }
        public string BEHAVIORCONTENT { get; set; }
        public string BEHAVIORFREQ { get; set; }
        public string ACTIVITY { get; set; }
        public string TALKEDWILLING { get; set; }
        public string NOTTALKED { get; set; }
        public string ARTACTIVITY { get; set; }
        public string AIDSACTIVITY { get; set; }
        public string SEVEREACTIVITY { get; set; }
        public string TALKEDNOWILLING { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string ORGID { get; set; }
    }
}
