//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_BILL
    {
        public LTC_BILL()
        {
            this.LTC_PAYBILL = new HashSet<LTC_PAYBILL>();
        }
    
        public long ID { get; set; }
        public string BILLNO { get; set; }
        public string BILLTYPE { get; set; }
        public Nullable<System.DateTime> BILLDATE { get; set; }
        public Nullable<System.DateTime> BILLENDDATE { get; set; }
        public string BILLSTATE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public int REGNO { get; set; }
        public long FEENO { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_PAYBILL> LTC_PAYBILL { get; set; }
    }
}
