//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_OUTVALUE
    {
        public long OUTNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string CLASSTYPE { get; set; }
        public string OUTTYPE { get; set; }
        public Nullable<int> OUTVALUE { get; set; }
        public string COMMDESC { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
