//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTGROUP
    {
        public LTC_COSTGROUP()
        {
            this.LTC_COSTGROUPDTL = new HashSet<LTC_COSTGROUPDTL>();
        }
    
        public int ID { get; set; }
        public string GROUPNO { get; set; }
        public string GROUPNAME { get; set; }
        public string GROUPTYPE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_COSTGROUPDTL> LTC_COSTGROUPDTL { get; set; }
    }
}
