//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTITEM
    {
        public LTC_COSTITEM()
        {
            this.LTC_FIXEDCOST = new HashSet<LTC_FIXEDCOST>();
        }
    
        public int ID { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public string ITEMTYPE { get; set; }
        public string ITEMUNIT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_FIXEDCOST> LTC_FIXEDCOST { get; set; }
    }
}
