//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_GOODSSALE
    {
        public int Id { get; set; }
        public int GoodsId { get; set; }
        public string GoodsName { get; set; }
        public string No { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> SaleTime { get; set; }
        public string Remark { get; set; }
        public string OrgId { get; set; }
    }
}
