//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REFERRALREC
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string UNITNAME { get; set; }
        public string UNITCONTACTOR { get; set; }
        public string UNITADDRESS { get; set; }
        public string UNITTEL { get; set; }
        public string REASON { get; set; }
        public string QUESTIONSUMMARY { get; set; }
        public string SERVICESUMMARY { get; set; }
        public string SUGGESTION { get; set; }
        public string EMPNO { get; set; }
        public Nullable<System.DateTime> REPLYDATE { get; set; }
        public string REPLYDESC { get; set; }
        public string REPLYTYPE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
