//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CHECKITEM
    {
        public string ITEMCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string NORMALVALUE { get; set; }
        public string LOWBOUND { get; set; }
        public string UPBOUND { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPECODE { get; set; }
        public string GROUPCODE { get; set; }
    
        public virtual LTC_CHECKGROUP LTC_CHECKGROUP { get; set; }
        public virtual LTC_CHECKTYPE LTC_CHECKTYPE { get; set; }
    }
}
