//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PAINEVALREC
    {
        public LTC_PAINEVALREC()
        {
            this.LTC_PAINBODYPART = new HashSet<LTC_PAINBODYPART>();
        }
    
        public long SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string NEXTEVALUATEBY { get; set; }
        public string DIAGDESC { get; set; }
        public string TRANSFERPART { get; set; }
        public string COMA_E { get; set; }
        public string COMA_M { get; set; }
        public string COMA_V { get; set; }
        public string GCS { get; set; }
        public string CONSCIOUSNESS { get; set; }
        public string PAINEXPRESSION { get; set; }
        public string PAINREACTION { get; set; }
        public Nullable<bool> CANCELFLAG { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string CANCELREASON { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_PAINBODYPART> LTC_PAINBODYPART { get; set; }
    }
}
