//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CONSTRAINTREC
    {
        public LTC_CONSTRAINTREC()
        {
            this.LTC_CONSTRAINSBEVAL = new HashSet<LTC_CONSTRAINSBEVAL>();
        }
    
        public long SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public string CLASSTYPE { get; set; }
        public Nullable<int> DAYS { get; set; }
        public string REASON { get; set; }
        public string EXECREASON { get; set; }
        public string CONSTRAINTWAY { get; set; }
        public string BODYPART { get; set; }
        public string CONSTRAINTWAYCNT { get; set; }
        public Nullable<bool> CANCELFLAG { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string DURATION { get; set; }
        public string CANCELREASON { get; set; }
        public string CANCELEXECBY { get; set; }
        public Nullable<bool> CANCEL24FLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    
        public virtual ICollection<LTC_CONSTRAINSBEVAL> LTC_CONSTRAINSBEVAL { get; set; }
    }
}
