//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COMMFILE
    {
        public int ID { get; set; }
        public string TYPECODE { get; set; }
        public string TYPENAME { get; set; }
        public string ITEMNAME { get; set; }
        public string ORGID { get; set; }
    }
}
