//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_CONSULTREC
    {
        public LTC_CONSULTREC()
        {
            this.LTC_CONSULTCALLBACK = new HashSet<LTC_CONSULTCALLBACK>();
        }
    
        public long ID { get; set; }
        public string CONSULTANTNAME { get; set; }
        public Nullable<System.DateTime> CONSULTTIME { get; set; }
        public string CONSULTANTPHONE { get; set; }
        public string APPELLATION { get; set; }
        public string OLDMANNAME { get; set; }
        public string OLDMANSEX { get; set; }
        public Nullable<int> OLDMANAGE { get; set; }
        public string CHANNEL { get; set; }
        public string RESERVATIONBED { get; set; }
        public string EARNESTSTATUS { get; set; }
        public Nullable<float> EARNESTAMOUNT { get; set; }
        public string RECORDBY { get; set; }
        public string REMARK { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
    
        public virtual ICollection<LTC_CONSULTCALLBACK> LTC_CONSULTCALLBACK { get; set; }
    }
}
