//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_WORKITEM
    {
        public LTC_WORKITEM()
        {
            this.LTC_LOOKOVER = new HashSet<LTC_LOOKOVER>();
            this.LTC_WORKSUBITEM = new HashSet<LTC_WORKSUBITEM>();
        }
    
        public string ITEMCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMTYPE { get; set; }
        public Nullable<int> ORDER { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<LTC_LOOKOVER> LTC_LOOKOVER { get; set; }
        public virtual ICollection<LTC_WORKSUBITEM> LTC_WORKSUBITEM { get; set; }
    }
}
