//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGDISEASEHIS
    {
        public LTC_REGDISEASEHIS()
        {
            this.LTC_REGDISEASEHISDTL = new HashSet<LTC_REGDISEASEHISDTL>();
        }
    
        public int REGNO { get; set; }
        public Nullable<bool> HAVEOPERATION { get; set; }
        public string OPERATION { get; set; }
        public Nullable<bool> HAVEDRUGALLERGY { get; set; }
        public string DRUGALLERGY { get; set; }
        public Nullable<bool> HAVEFOODALLERGY { get; set; }
        public string FOODALLERGY { get; set; }
        public Nullable<bool> HAVETRANSFUSION { get; set; }
        public string ORIGMEDICALHOS { get; set; }
        public string EMERGENCYTRANSTO { get; set; }
        public Nullable<bool> ISAGREETRANSFER { get; set; }
        public string MEDICALHIS { get; set; }
        public string OTHERS { get; set; }
    
        public virtual LTC_REGFILE LTC_REGFILE { get; set; }
        public virtual ICollection<LTC_REGDISEASEHISDTL> LTC_REGDISEASEHISDTL { get; set; }
    }
}
