//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_FALLINCIDENTEVENT
    {
        public long ID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public string RECORDBY { get; set; }
        public string EVENTADDRESS { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public string EVENTTYPE { get; set; }
        public string EVENTDEGREE { get; set; }
        public string EVENTCAUSE { get; set; }
        public string CONSCIOUSSTATE { get; set; }
        public string EMOTIONALSTATE { get; set; }
        public string SIGNS { get; set; }
        public string EVENTDESC { get; set; }
        public string SETTLEBY { get; set; }
        public Nullable<System.DateTime> VISITDOCDATE { get; set; }
        public string HOSPNAME { get; set; }
        public string NOTIFYPEOPLE { get; set; }
        public Nullable<bool> NOTIFYGOVFLAG { get; set; }
        public Nullable<System.DateTime> NOTIFYDATE { get; set; }
        public string CONSCIOUSSTATE_A { get; set; }
        public string EMOTIONSTATE_A { get; set; }
        public string SETTLERESULT { get; set; }
        public string FOLLOWUPINSTRUCTIONS { get; set; }
        public string MEDICALDISPUTE { get; set; }
        public string AFFECTS { get; set; }
        public string AFFECTSDESC { get; set; }
        public string IMPROVEMENT { get; set; }
        public string DESCRIPTION { get; set; }
        public string ORGID { get; set; }
        public string PICT1 { get; set; }
        public string PICT2 { get; set; }
    }
}
