//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PREIPD
    {
        public long PREFEENO { get; set; }
        public string RECSTATUS { get; set; }
        public string SOURCETYPE { get; set; }
        public string INSMARK { get; set; }
        public Nullable<System.DateTime> PREDATE { get; set; }
        public string DEPTNO { get; set; }
        public string BEDNO { get; set; }
        public string COMMDESC { get; set; }
        public Nullable<bool> WAITFLAG { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
        public string ORGID { get; set; }
        public string CONTACTTEL { get; set; }
        public string CONTACTNAME { get; set; }
        public string CANCELREASON { get; set; }
        public string PNAME { get; set; }
        public string SEX { get; set; }
        public Nullable<int> AGE { get; set; }
        public string IDNO { get; set; }
        public string Phone { get; set; }
    }
}
