//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_RESIDENTBALANCE
    {
        public LTC_RESIDENTBALANCE()
        {
            this.LTC_PRECHARGE = new HashSet<LTC_PRECHARGE>();
            this.LTC_RESIDENTBALANCEREFUND = new HashSet<LTC_RESIDENTBALANCEREFUND>();
        }
    
        public string BALANCEID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public decimal DEPOSIT { get; set; }
        public decimal BLANCE { get; set; }
        public Nullable<decimal> TOTALPAYMENT { get; set; }
        public Nullable<decimal> TOTALCOST { get; set; }
        public Nullable<decimal> TOTALNCIPAY { get; set; }
        public Nullable<decimal> TOTALNCIOVERSPEND { get; set; }
        public bool ISHAVENCI { get; set; }
        public Nullable<decimal> NCIPAYLEVEL { get; set; }
        public Nullable<decimal> NCIPAYSCALE { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<LTC_PRECHARGE> LTC_PRECHARGE { get; set; }
        public virtual ICollection<LTC_RESIDENTBALANCEREFUND> LTC_RESIDENTBALANCEREFUND { get; set; }
    }
}
