//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_VISITDEPT
    {
        public LTC_VISITDEPT()
        {
            this.LTC_VISITDOCTOR = new HashSet<LTC_VISITDOCTOR>();
        }
    
        public string DEPTNO { get; set; }
        public string DEPTNAME { get; set; }
        public string HOSPNO { get; set; }
    
        public virtual LTC_VISITHOSPITAL LTC_VISITHOSPITAL { get; set; }
        public virtual ICollection<LTC_VISITDOCTOR> LTC_VISITDOCTOR { get; set; }
    }
}
