//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_PIPELINEREC
    {
        public int SEQNO { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public string PIPELINENAME { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<bool> REMOVEFLAG { get; set; }
        public string REMOVETRAIN { get; set; }
        public Nullable<bool> REMOVEDFLAG { get; set; }
        public Nullable<System.DateTime> REMOVEDATE { get; set; }
        public string REMOVEREASON { get; set; }
        public string REMOVEBY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
    }
}
