//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_LOG
    {
        public long ID { get; set; }
        public string USERNAME { get; set; }
        public string IP { get; set; }
        public string HOSTNAME { get; set; }
        public Nullable<System.DateTime> LOGINTIME { get; set; }
    }
}
