//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_ORGROOM
    {
        public string ROOMNO { get; set; }
        public string FLOORID { get; set; }
        public string ROOMNAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public string AREA { get; set; }
        public string ROOMTYPE { get; set; }
        public string ORGID { get; set; }
    
        public virtual LTC_ORGFLOOR LTC_ORGFLOOR { get; set; }
    }
}
