//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_COSTGROUPDTL
    {
        public int ID { get; set; }
        public int GROUPID { get; set; }
        public string COSTITEMNO { get; set; }
        public string COSTNAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PERIOD { get; set; }
        public Nullable<int> REPEATCOUNT { get; set; }
        public Nullable<int> COSTITEMID { get; set; }
        public string ITEMUNIT { get; set; }
    
        public virtual LTC_COSTGROUP LTC_COSTGROUP { get; set; }
    }
}
