//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_IPDVERIFY
    {
        public int ID { get; set; }
        public long FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<decimal> SUBSIDYAMT { get; set; }
        public string SUBSIDYWAY { get; set; }
        public string SUBSIDYUNIT { get; set; }
        public Nullable<decimal> FEERATE { get; set; }
        public string APPLYDOCNO { get; set; }
        public Nullable<System.DateTime> APPLYDATE { get; set; }
        public Nullable<System.DateTime> EXPIREDATE { get; set; }
        public string APPROVEDOCNO { get; set; }
        public Nullable<System.DateTime> APPROVEDATE { get; set; }
        public string INSTYPE { get; set; }
        public string BANKNAME { get; set; }
        public string BANKACCOUNTNO { get; set; }
        public string OTHERACCOUNTNO { get; set; }
        public Nullable<decimal> DEPOSITBALANCE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
