//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_SCENARIO_ITEM
    {
        public LTC_SCENARIO_ITEM()
        {
            this.LTC_SCENARIO_ITEM_OPTION = new HashSet<LTC_SCENARIO_ITEM_OPTION>();
        }
    
        public int ID { get; set; }
        public int CATEGORYID { get; set; }
        public Nullable<int> GROUPID { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public string ITEMNAME { get; set; }
    
        public virtual LTC_SCENARIO LTC_SCENARIO { get; set; }
        public virtual ICollection<LTC_SCENARIO_ITEM_OPTION> LTC_SCENARIO_ITEM_OPTION { get; set; }
    }
}
