//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_REGQUESTION
    {
        public long RECORDID { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<long> FEENO { get; set; }
        public Nullable<int> REGNO { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public Nullable<int> EVALNUMBER { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string ENVRESULTS { get; set; }
        public string DESCRIPTION { get; set; }
        public string EVALUATEBY { get; set; }
        public Nullable<System.DateTime> EVALDATE { get; set; }
        public Nullable<System.DateTime> NEXTEVALDATE { get; set; }
        public string NEXTEVALUATEBY { get; set; }
        public string NOTEVALREASON { get; set; }
        public string ORGID { get; set; }
        public string CAUSEREASON { get; set; }
        public string LASTCOMPARE { get; set; }
    }
}
