//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NCIFINANCIALMONTH
    {
        public string MONTH { get; set; }
        public string STARTDATE { get; set; }
        public string ENDDATE { get; set; }
        public string GOVID { get; set; }
    }
}
