//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_NOTIFICATION
    {
        public int ID { get; set; }
        public string SUBJECTS { get; set; }
        public string CONTENTS { get; set; }
        public string DOCTYPE { get; set; }
        public string DOCUMENTNO { get; set; }
        public string RECORDBY { get; set; }
        public Nullable<System.DateTime> RECORDDATE { get; set; }
        public Nullable<System.DateTime> EXPRIEDATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATEBY { get; set; }
        public string ORGID { get; set; }
    }
}
