//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_MAKERITEM
    {
        public int MAKERID { get; set; }
        public string MAKENAME { get; set; }
        public Nullable<int> SHOWNUMBER { get; set; }
        public Nullable<bool> ISSHOW { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string DATATYPE { get; set; }
        public Nullable<int> LIMITEDID { get; set; }
        public string CATEGORY { get; set; }
    }
}
