//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTC_HANDOVERDTL
    {
        public long ID { get; set; }
        public long RECORDID { get; set; }
        public long FEENO { get; set; }
        public string ITEMCODE { get; set; }
        public Nullable<int> ORDER { get; set; }
        public string CONTENT { get; set; }
        public string RECORDBY { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    
        public virtual LTC_HANDOVERRECORD LTC_HANDOVERRECORD { get; set; }
    }
}
