//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_SERVICEBAK
    {
        public string SERVICECODE { get; set; }
        public string MCRULEID { get; set; }
        public string SERVICENAME { get; set; }
        public string SERVICEDESC { get; set; }
        public string UNITS { get; set; }
        public Nullable<decimal> GUIDEPRICE { get; set; }
        public Nullable<decimal> MAXPRICE { get; set; }
        public string COMMENT { get; set; }
        public string PINYIN { get; set; }
        public int STATUS { get; set; }
        public Nullable<System.DateTime> BAKTIME { get; set; }
        public string BAKBY { get; set; }
    }
}
