//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_CARETYPE
    {
        public NCI_CARETYPE()
        {
            this.NCIA_CARETYPECONDITION = new HashSet<NCIA_CARETYPECONDITION>();
            this.NCI_NURSINGHOME = new HashSet<NCI_NURSINGHOME>();
        }
    
        public int CARETYPEID { get; set; }
        public int CARETYPE { get; set; }
        public string DISPLAYNAME { get; set; }
        public string CARETYPENAME { get; set; }
        public decimal NCIPAYLEVEL { get; set; }
        public decimal NCIPAYLEVELOUT { get; set; }
        public decimal NCIPAYSCALE { get; set; }
        public decimal NCIPAYSCALEOUT { get; set; }
    
        public virtual ICollection<NCIA_CARETYPECONDITION> NCIA_CARETYPECONDITION { get; set; }
        public virtual ICollection<NCI_NURSINGHOME> NCI_NURSINGHOME { get; set; }
    }
}
