//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_AGENCY
    {
        public NCI_AGENCY()
        {
            this.NCI_AGENCYSTAFF = new HashSet<NCI_AGENCYSTAFF>();
        }
    
        public string AGENCYID { get; set; }
        public string GOVID { get; set; }
        public string AGENCYNAME { get; set; }
        public string AGENCYNO { get; set; }
        public string CONTACT { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string CREATBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCI_GOVERNMENT NCI_GOVERNMENT { get; set; }
        public virtual ICollection<NCI_AGENCYSTAFF> NCI_AGENCYSTAFF { get; set; }
    }
}
