//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_LOCATIONCODE
    {
        public NCI_LOCATIONCODE()
        {
            this.NCI_GOVERNMENT = new HashSet<NCI_GOVERNMENT>();
        }
    
        public int LOCATIONID { get; set; }
        public string LOCATIONNAME { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string FULLNAME { get; set; }
    
        public virtual ICollection<NCI_GOVERNMENT> NCI_GOVERNMENT { get; set; }
    }
}
