//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_SUPERVISE
    {
        public int ID { get; set; }
        public string APPLICANTID { get; set; }
        public Nullable<int> APPCERTID { get; set; }
        public Nullable<int> APPHOSPID { get; set; }
        public int TYPE { get; set; }
        public string REASON { get; set; }
        public string RESTORE { get; set; }
        public int STATUS { get; set; }
        public bool VALID { get; set; }
        public Nullable<System.DateTime> CANCLETIME { get; set; }
        public Nullable<System.DateTime> RESTORETIME { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
    }
}
