//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_INSURANCECOMPANY
    {
        public NCI_INSURANCECOMPANY()
        {
            this.NCI_INSURANCECOMPANYSTAFF = new HashSet<NCI_INSURANCECOMPANYSTAFF>();
        }
    
        public string ICID { get; set; }
        public string GOVID { get; set; }
        public string ICNAME { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string PHONE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCI_GOVERNMENT NCI_GOVERNMENT { get; set; }
        public virtual ICollection<NCI_INSURANCECOMPANYSTAFF> NCI_INSURANCECOMPANYSTAFF { get; set; }
    }
}
