//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_CODEFILE
    {
        public NCI_CODEFILE()
        {
            this.NCI_CODEDTL = new HashSet<NCI_CODEDTL>();
        }
    
        public string ITEMTYPE { get; set; }
        public string TYPENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string MODIFYFLAG { get; set; }
        public Nullable<System.DateTime> UPDATEDATE { get; set; }
        public string UPDATEBY { get; set; }
    
        public virtual ICollection<NCI_CODEDTL> NCI_CODEDTL { get; set; }
    }
}
