//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_ROLE
    {
        public NCI_ROLE()
        {
            this.NCI_ROLE_MODULE = new HashSet<NCI_ROLE_MODULE>();
            this.NCI_USER = new HashSet<NCI_USER>();
        }
    
        public string ROLEID { get; set; }
        public string PARENTROLEID { get; set; }
        public string ROLENAME { get; set; }
        public string ROLETYPE { get; set; }
        public string DESC { get; set; }
        public int STATUS { get; set; }
        public int ORGTYPE { get; set; }
        public string ORGID { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCI_ROLE_MODULE> NCI_ROLE_MODULE { get; set; }
        public virtual ICollection<NCI_USER> NCI_USER { get; set; }
    }
}
