//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_GOVERNMENT
    {
        public NCI_GOVERNMENT()
        {
            this.NCI_AGENCY = new HashSet<NCI_AGENCY>();
            this.NCI_GOVERNMENTSTAFF = new HashSet<NCI_GOVERNMENTSTAFF>();
            this.NCI_INSURANCECOMPANY = new HashSet<NCI_INSURANCECOMPANY>();
            this.NCI_NURSINGHOME = new HashSet<NCI_NURSINGHOME>();
        }
    
        public string GOVID { get; set; }
        public Nullable<int> GOVERMENTLEVELID { get; set; }
        public Nullable<int> LOCATIONID { get; set; }
        public string GOVNAME { get; set; }
        public string PARENTGOVID { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT { get; set; }
        public string PHONE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCI_AGENCY> NCI_AGENCY { get; set; }
        public virtual NCI_GOVERNMENTLEVEL NCI_GOVERNMENTLEVEL { get; set; }
        public virtual NCI_LOCATIONCODE NCI_LOCATIONCODE { get; set; }
        public virtual ICollection<NCI_GOVERNMENTSTAFF> NCI_GOVERNMENTSTAFF { get; set; }
        public virtual ICollection<NCI_INSURANCECOMPANY> NCI_INSURANCECOMPANY { get; set; }
        public virtual ICollection<NCI_NURSINGHOME> NCI_NURSINGHOME { get; set; }
    }
}
