//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCI_ROLE_MODULE
    {
        public string MODULEID { get; set; }
        public string ROLEID { get; set; }
        public string MODULESETTING { get; set; }
    
        public virtual NCI_MODULES NCI_MODULES { get; set; }
        public virtual NCI_ROLE NCI_ROLE { get; set; }
    }
}
