//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_NURSINGHOMEASSTRECORD
    {
        public NCIA_NURSINGHOMEASSTRECORD()
        {
            this.NCIA_APPCERT = new HashSet<NCIA_APPCERT>();
            this.NCIA_NURSINGHOMEASSTRECORDDETAIL = new HashSet<NCIA_NURSINGHOMEASSTRECORDDETAIL>();
        }
    
        public int NSASSTRECORDID { get; set; }
        public int APPCERTID { get; set; }
        public int TOTALSCORE { get; set; }
        public System.DateTime ASSTDATE { get; set; }
        public int ISEXPIRED { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCIA_APPCERT> NCIA_APPCERT { get; set; }
        public virtual ICollection<NCIA_NURSINGHOMEASSTRECORDDETAIL> NCIA_NURSINGHOMEASSTRECORDDETAIL { get; set; }
    }
}
