//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_CARETYPECONDITION
    {
        public NCIA_CARETYPECONDITION()
        {
            this.NCIA_APPCERT = new HashSet<NCIA_APPCERT>();
        }
    
        public int CCCID { get; set; }
        public string NSID { get; set; }
        public int CARETYPEID { get; set; }
        public string CCCNAME { get; set; }
        public string CCCDESC { get; set; }
    
        public virtual NCI_CARETYPE NCI_CARETYPE { get; set; }
        public virtual NCI_NURSINGHOME NCI_NURSINGHOME { get; set; }
        public virtual ICollection<NCIA_APPCERT> NCIA_APPCERT { get; set; }
    }
}
