//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_DEDUCTION
    {
        public int ID { get; set; }
        public Nullable<long> NSMONFEEID { get; set; }
        public string NSNO { get; set; }
        public string RESIDENTSSID { get; set; }
        public int DEDUCTIONTYPE { get; set; }
        public string DEBITMONTH { get; set; }
        public Nullable<int> DEBITDAYS { get; set; }
        public double AMOUNT { get; set; }
        public string DEDUCTIONREASON { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CREATEBY { get; set; }
        public System.DateTime CREATTIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCIP_NSMONFEE NCIP_NSMONFEE { get; set; }
    }
}
