//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_APPLICANTHISTORY
    {
        public int ID { get; set; }
        public string APPLICANTID { get; set; }
        public string NSID { get; set; }
        public string IDNO { get; set; }
        public string NAME { get; set; }
        public string GENDER { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public string SSNO { get; set; }
        public string RESIDENCE { get; set; }
        public Nullable<int> MCTYPE { get; set; }
        public string DISEASE { get; set; }
        public string DISEASEDESC { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string FAMILYMEMBERNAME { get; set; }
        public string FAMILYMEMBERPHONE { get; set; }
        public string OCCUPATION { get; set; }
        public string NATIVEPLACE { get; set; }
        public string MARITALSTATUS { get; set; }
        public string ECONOMYSTATUS { get; set; }
        public string LIVECONDITION { get; set; }
        public string HOUSINGPROPERTY { get; set; }
        public string HABITHOS { get; set; }
        public Nullable<int> ZIP { get; set; }
        public string FAMILYMEMBERRELATIONSHIP { get; set; }
        public Nullable<int> LASTCERTRESULT { get; set; }
        public Nullable<System.DateTime> LASTCERTDATE { get; set; }
        public Nullable<int> LASTHOSPRESULT { get; set; }
        public Nullable<System.DateTime> LASTHOSPDATE { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
