//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIA_NSAPPCERTRATE
    {
        public int ID { get; set; }
        public string NSID { get; set; }
        public decimal PASSRATE { get; set; }
        public string YEAR { get; set; }
        public long TOTALPEOPLE { get; set; }
        public long PASSPEOPLE { get; set; }
        public System.DateTime UPDATETIME { get; set; }
    
        public virtual NCI_NURSINGHOME NCI_NURSINGHOME { get; set; }
    }
}
