//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_SERVICEDEPOSIT
    {
        public NCIP_SERVICEDEPOSIT()
        {
            this.NCIP_NCIPAYGRANT = new HashSet<NCIP_NCIPAYGRANT>();
        }
    
        public int SERVICEDEPOSITID { get; set; }
        public Nullable<int> SDGRANTID { get; set; }
        public string NSID { get; set; }
        public string YEARMONTH { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime SERVICEDEPOSITDATE { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCIP_NCIPAYGRANT> NCIP_NCIPAYGRANT { get; set; }
        public virtual NCIP_SERVICEDEPOSITGRANT NCIP_SERVICEDEPOSITGRANT { get; set; }
    }
}
