//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_NSMONFEE
    {
        public NCIP_NSMONFEE()
        {
            this.NCIA_DEDUCTION = new HashSet<NCIA_DEDUCTION>();
            this.NCIP_RESIDENTMONFEE = new HashSet<NCIP_RESIDENTMONFEE>();
        }
    
        public long NSMONFEEID { get; set; }
        public Nullable<int> NCIPAYGRANTID { get; set; }
        public string NSID { get; set; }
        public string NSNO { get; set; }
        public string YEARMONTH { get; set; }
        public int TOTALRESIDENT { get; set; }
        public int TOTALHOSPDAY { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public decimal TOTALNCIPAY { get; set; }
        public int STATUS { get; set; }
        public string CREATORNAME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCIA_DEDUCTION> NCIA_DEDUCTION { get; set; }
        public virtual NCIP_NCIPAYGRANT NCIP_NCIPAYGRANT { get; set; }
        public virtual ICollection<NCIP_RESIDENTMONFEE> NCIP_RESIDENTMONFEE { get; set; }
    }
}
