//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_SERVICEDEPOSITGRANT
    {
        public NCIP_SERVICEDEPOSITGRANT()
        {
            this.NCIP_SERVICEDEPOSIT = new HashSet<NCIP_SERVICEDEPOSIT>();
        }
    
        public int SDGRANTID { get; set; }
        public string NSID { get; set; }
        public string YEAR { get; set; }
        public decimal DUEOFPAY { get; set; }
        public decimal ACTRUALPAY { get; set; }
        public Nullable<decimal> DECUT { get; set; }
        public string DECUTREASON { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual ICollection<NCIP_SERVICEDEPOSIT> NCIP_SERVICEDEPOSIT { get; set; }
    }
}
