//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_RESIDENTMONFEE
    {
        public NCIP_RESIDENTMONFEE()
        {
            this.NCIP_RESIDENTMONFEEDTL = new HashSet<NCIP_RESIDENTMONFEEDTL>();
        }
    
        public long RSMONFEEID { get; set; }
        public Nullable<long> NSMONFEEID { get; set; }
        public Nullable<long> FEENO { get; set; }
        public string NSID { get; set; }
        public Nullable<int> CARETYPE { get; set; }
        public string RESIDENTSSID { get; set; }
        public string CERTNO { get; set; }
        public System.DateTime HOSPENTRYDATE { get; set; }
        public System.DateTime HOSPDISCHARGEDATE { get; set; }
        public int HOSPDAY { get; set; }
        public decimal NCIPAYLEVEL { get; set; }
        public decimal NCIPAYSCALE { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public decimal NCIPAY { get; set; }
        public int STATUS { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCIP_NSMONFEE NCIP_NSMONFEE { get; set; }
        public virtual ICollection<NCIP_RESIDENTMONFEEDTL> NCIP_RESIDENTMONFEEDTL { get; set; }
    }
}
