//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_NCIPAYGRANT
    {
        public NCIP_NCIPAYGRANT()
        {
            this.NCIP_NSMONFEE = new HashSet<NCIP_NSMONFEE>();
        }
    
        public int GRANTID { get; set; }
        public Nullable<int> SERVICEDEPOSITID { get; set; }
        public string NSID { get; set; }
        public string GRANTYEAR { get; set; }
        public int TOTALRESIDENT { get; set; }
        public int TOTALHOSPDAY { get; set; }
        public decimal TOTALAMOUNT { get; set; }
        public decimal TOTALNCIPAY { get; set; }
        public int STATUS { get; set; }
        public string CREATORNAME { get; set; }
        public int ICRESULT { get; set; }
        public string ICCOMMENT { get; set; }
        public Nullable<System.DateTime> ICOPERATETIME { get; set; }
        public string ICUSERID { get; set; }
        public string ICID { get; set; }
        public Nullable<int> AGENCYRESULT { get; set; }
        public string AGENCYCOMMENT { get; set; }
        public Nullable<System.DateTime> AGENCYOPERATETIME { get; set; }
        public string AGENCYUSERID { get; set; }
        public string AGENCYID { get; set; }
        public Nullable<System.DateTime> GRANTTIME { get; set; }
        public Nullable<decimal> ADJUSTAMOUNT { get; set; }
        public string ADJUSTREASON { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCIP_SERVICEDEPOSIT NCIP_SERVICEDEPOSIT { get; set; }
        public virtual ICollection<NCIP_NSMONFEE> NCIP_NSMONFEE { get; set; }
    }
}
