//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCIP_RESIDENTMONFEEDTL
    {
        public long RSMONFEEDTLID { get; set; }
        public Nullable<long> RSMONFEEID { get; set; }
        public string FEENAME { get; set; }
        public string FEETYPE { get; set; }
        public string MCCODE { get; set; }
        public decimal UNITPRICE { get; set; }
        public decimal QTY { get; set; }
        public Nullable<bool> ISNCIITEM { get; set; }
        public decimal AMOUNT { get; set; }
        public System.DateTime TAKETIME { get; set; }
        public string OPERATORNAME { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    
        public virtual NCIP_RESIDENTMONFEE NCIP_RESIDENTMONFEE { get; set; }
    }
}
