//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_CODERULE
    {
        public string ORGID { get; set; }
        public string CODEKEY { get; set; }
        public string FLAGRULE { get; set; }
        public string GENERATERULE { get; set; }
        public string FLAG { get; set; }
        public Nullable<int> SERIALNUMBER { get; set; }
    }
}
