//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_REPORT
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string MAJORTYPE { get; set; }
        public string REPORTTYPE { get; set; }
        public string FilterType { get; set; }
        public Nullable<bool> IsFeeNoRequired { get; set; }
        public string SYSTYPE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string ORGID { get; set; }
    }
}
