//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSG_ANSWER
    {
        public TSG_ANSWER()
        {
            this.TSG_ANSWERDTL = new HashSet<TSG_ANSWERDTL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> QUESTIONID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDERSEQ { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string UPDATER { get; set; }
        public Nullable<System.DateTime> UPDATETIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TSG_QUESTION TSG_QUESTION { get; set; }
        public virtual ICollection<TSG_ANSWERDTL> TSG_ANSWERDTL { get; set; }
    }
}
