//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSG_CATEGORY
    {
        public TSG_CATEGORY()
        {
            this.TSG_QUESTION = new HashSet<TSG_QUESTION>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<TSG_QUESTION> TSG_QUESTION { get; set; }
    }
}
