//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMHC.SLTC.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSG_ANSWERDTL
    {
        public int ID { get; set; }
        public Nullable<int> ANSWERID { get; set; }
        public string NAME { get; set; }
        public string ANSDTLIMAGEURL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDERSEQ { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual TSG_ANSWER TSG_ANSWER { get; set; }
    }
}
